language: objective-c
osx_image: xcode9
script:
  xcodebuild -project TinyWatchCalc.xcodeproj -destination 'platform=iOS Simulator,id=179E026C-281B-4404-B877-C0773E6A5C0C,OS=11.0' -scheme Calculator build test